// Generated by CoffeeScript 1.10.0
(function() {
  var CND, TC, badge, debug, echo, help, include, info, log, rpr, test, urge, warn, whisper,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'TOPOCACHE/TESTS';

  log = CND.get_logger('plain', badge);

  debug = CND.get_logger('debug', badge);

  info = CND.get_logger('info', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  test = require('guy-test');

  TC = require('./main');

  this._prune = function() {
    var name, value;
    for (name in this) {
      value = this[name];
      if (name.startsWith('_')) {
        continue;
      }
      if (indexOf.call(include, name) < 0) {
        delete this[name];
      }
    }
    return null;
  };

  this._main = function() {
    return test(this, {
      'timeout': 3000
    });
  };

  this["demo"] = function(T, done) {
    var cache, f, fc, fp, g, gc, gp, h, hc, hp;
    cache = {};
    fc = function() {
      return cache['f'];
    };
    fp = function() {
      return cache['f'] = g() + h();
    };
    f = function() {
      var R;
      if ((R = fc()) != null) {
        return R;
      }
      return fp();
    };
    gc = function() {
      return cache['g'];
    };
    gp = function() {
      return cache['g'] = 2 + 3;
    };
    g = function() {
      var R;
      if ((R = gc()) != null) {
        return R;
      }
      return gp();
    };
    hc = function() {
      return cache['h'];
    };
    hp = function() {
      return cache['h'] = 4 + 5;
    };
    h = function() {
      var R;
      if ((R = hc()) != null) {
        return R;
      }
      return hp();
    };
    info(f());
    return done();
  };

  if (module.parent == null) {
    include = ["demo"];
    this._prune();
    this._main();
  }

}).call(this);

//# sourceMappingURL=tests.js.map
